---
- name: update apt repositories cache
  apt: update_cache=yes cache_valid_time=14400

- name: install packages
  apt: pkg={{item}} state=installed
  with_items:
    - libcairo2-dev
    - libpango1.0-dev
    - librrd-dev
    - python-rrdtool
    - python-dev
    - libxml2-dev 
    - libxslt-dev
    - zlib1g-dev
    - python-psycopg2
    - python-virtualenv
    - libffi-dev
